### ISSUE TITLE
Cursor sorunu

### ISSUE THREAD

**Issue by fatihydrm** [mertssmnoglu/LinuxShellClone#9]
Window'un herhangi bir kısmına tıklanınca cursor kayboluyor fixlenmesi gerek sanırım 😃

**Comment by mertssmnoglu** [comment]
Ufak bir güncelleme getirdim şuan [sitede](https://mertssmnoglu.github.io/LinuxShellClone/) yayında. Rica etsem bakabilir misin?

**Comment by fatihydrm** [comment]
Sorun giderilmiş elinize sağlık 😃

**Comment by mertssmnoglu** [comment]
Teşekkürler 😃, iyi çalışmalar dilerim
